version: '3.8'

services:
  online:
    build:
      context: .
      args:
        - NODE_ENV=online
      dockerfile: Dockerfile
    image: boting-tattoo-online:latest
    container_name: boting-tattoo-online
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/server/certs:/etc/nginx/ssl
      - /var/server/certbot-etc:/var/lib/letsencrypt
      - /var/server/certbot-www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
    environment:
      - NODE_ENV=online
    env_file:
      - .env.online
    profiles:
      - online

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /var/server/certs:/etc/letsencrypt
      - /var/server/certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"