version: '3.8'

services:
  online:
    build:
      context: .
      args:
        - NODE_ENV=online
      dockerfile: Dockerfile
    image: boting-tattoo-online:latest
    container_name: boting-tattoo-online
    ports:
      - "80:80"
    environment:
      - NODE_ENV=online
    env_file:
      - .env.online
    profiles:
      - online