server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # 返回 404 錯誤
    return 404;
}

server {
    listen 80;
    server_name bottingtattoo.com

    root /usr/share/nginx/html;
    index index.html index.htm;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    charset utf-8;

    # 強制跳轉到 HTTPS（如果您有 SSL 證書的話）
    # return 301 https://$server_name$request_uri;

    # 安全性設置
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline'; font-src * data:;" always;
    # add_header Content-Security-Policy "default-src 'self' http: https: data: 'unsafe-inline' 'unsafe-eval'; font-src 'self' http: https: data: fonts.gstatic.com; style-src 'self' 'unsafe-inline' http: https: fonts.googleapis.com;" always;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # 靜態文件緩存
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }

    # location / {
    #     try_files $uri $uri/ /index.html;
    # }

    location / {
        proxy_pass http://34.81.11.215:8080;  # 将请求转发到指定的IP和端口
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        try_files $uri $uri/ /index.html;
    }

    # location /api/ws {
    #     proxy_pass http://119.8.53.204:7778;
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "upgrade";
    #     proxy_set_header Host $host;
    # }

    # location /api {
    #     proxy_pass http://119.8.53.204:7778/api;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;

    #     # 超時設置
    #     proxy_connect_timeout 60s;
    #     proxy_send_timeout 60s;
    #     proxy_read_timeout 60s;
    # }

    # 禁止訪問隱藏文件
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    # 錯誤頁面配置
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        internal;
    }

    # 日誌配置
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}