name: Deploy

on:
    push:
        branches:
            - online

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Server
              run: |
                  ssh -o StrictHostKeyChecking=no gcpn01@34.81.11.215 'bash -s' < /var/server/deploy_shells/boting-tattoo.sh
