name: Deploy

on:
    push:
        branches:
            - online

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Test SSH Connection
              run: |
                  ssh -o StrictHostKeyChecking=no gcpn01@34.81.11.215 'echo "SSH connection successful"'

            - name: List Directory Contents
              run: |
                  ssh -o StrictHostKeyChecking=no gcpn01@34.81.11.215 'ls -l /var/server/deploy_shells/'

            - name: Deploy to Server
              env:
                  ENVIRONMENT: ${{ github.ref_name }}
              run: |
                  ssh -o StrictHostKeyChecking=no gcpn01@34.81.11.215 'bash /var/server/deploy_shells/boting-tattoo.sh ${{ github.ref_name }}'
